-- MySQL Script generated by MySQL Workbench
-- 05/26/16 17:14:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema equipoECCI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema equipoECCI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equipoECCI` DEFAULT CHARACTER SET utf8 ;
USE `equipoECCI` ;

-- -----------------------------------------------------
-- Table `equipoECCI`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipoECCI`.`users` ;

CREATE TABLE IF NOT EXISTS `equipoECCI`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` INT NULL,
  `foto_id` LONGBLOB NULL,
  `role` VARCHAR(20) NULL,
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipoECCI`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipoECCI`.`tickets` ;

CREATE TABLE IF NOT EXISTS `equipoECCI`.`tickets` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `modelo` VARCHAR(20) NULL,
  `serie` VARCHAR(30) NULL,
  `marca` VARCHAR(15) NULL,
  `codigo_QR` LONGBLOB NULL,
  `placa_universitaria` VARCHAR(30) NULL,
  `tipo_activo` VARCHAR(15) NULL,
  `observaciones` VARCHAR(80) NULL,
  `fecha_solicitud` DATE NULL,
  `fecha_expiracion` DATE NULL DEFAULT 1000-01-01,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipoECCI`.`users_has_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipoECCI`.`users_has_tickets` ;

CREATE TABLE IF NOT EXISTS `equipoECCI`.`users_has_tickets` (
  `users_id` INT UNSIGNED NOT NULL,
  `tickets_id` INT NOT NULL,
  `tipo` TINYINT(2) NOT NULL,
  PRIMARY KEY (`users_id`, `tickets_id`, `tipo`),
  INDEX `fk_users_has_tickets_tickets1_idx` (`tickets_id` ASC),
  INDEX `fk_users_has_tickets_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_tickets_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `equipoECCI`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tickets_tickets1`
    FOREIGN KEY (`tickets_id`)
    REFERENCES `equipoECCI`.`tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `equipoECCI`;

DELIMITER $$

USE `equipoECCI`$$
DROP TRIGGER IF EXISTS `equipoECCI`.`tickets_AFTER_INSERT` $$
USE `equipoECCI`$$
CREATE DEFINER = CURRENT_USER TRIGGER `equipoECCI`.`tickets_AFTER_INSERT` AFTER INSERT ON `tickets` FOR EACH ROW
BEGIN
 DECLARE annio INT;
  SET @annio := (SELECT EXTRACT(YEAR FROM fecha_solicitud));
INSERT INTO tickets (fecha_expiracion)
  VALUES (CONCAT(@annio, RIGHT(fecha_expiracion,6)));
END$$


DELIMITER ;
